# Emulator Plugin + Synse Server via TCP
version: "3"
services:

  # Synse Server
  synse-server:
    container_name: synse-server
    image: vaporio/synse-server:2.0.0
    ports:
      - 5000:5000
    # TCP-based plugins can be registered with Synse Server via
    # environment variables, so we specify the plugin here.
    environment:
      SYNSE_PLUGIN_TCP_EMULATOR: emulator-plugin:5001
    links:
      - emulator-plugin

  # Emulator Plugin
  # while it is unnecessary to run this externally (as it is built-in to
  # the Synse Server image), doing so here provides an example of how
  # to set up plugins with Synse Server that is testable without any
  # hardware dependencies.
  emulator-plugin:
    container_name: emulator-plugin
    image: vaporio/emulator-plugin
    volumes:
      # mount in the plugin config (see the environment section on how to
      # reference this non-default location)
      - ./config/tcp:/tmp/config/
      # mount in the device/proto config to the default path
      - ../../config:/etc/synse/plugin/config
    ports:
      - 5001:5001
    environment:
      # sets the override location for the plugin configuration
      PLUGIN_CONFIG: /tmp/config
