# Emulator Plugin + Synse Server via Unix Socket
version: "3.3"
services:

  # Synse Server
  synse-server:
    container_name: synse-server
    image: vaporio/synse-server:2.0.0
    ports:
      - 5000:5000
    # Unix-based plugins can be registered with Synse Server when Synse Server
    # detects the socket file in a well-known path. Here, we mount a shared
    # volume to that path so that Synse Server can access the plugin's socket.
    volumes:
      - type: volume
        source: plugin_sockets
        target: /tmp/synse/procs

  # Emulator Plugin
  # while it is unnecessary to run this externally (as it is built-in to
  # the Synse Server image), doing so here provides an example of how
  # to set up plugins with Synse Server that is testable without any
  # hardware dependencies.
  emulator-plugin:
    container_name: emulator-plugin
    image: vaporio/emulator-plugin
    environment:
      # sets the override location for the plugin configuration
      PLUGIN_CONFIG: /tmp/config
    volumes:
      # mount in the device/proto config to the default path
      - ../../config:/etc/synse/plugin/config
      # mount in the plugin config (see the environment section on how to
      # reference this non-default location)
      - ./config/unix:/tmp/config/
      # volume for the plugin socket, shared with synse-server
      - type: volume
        source: plugin_sockets
        target: /tmp/synse/procs

volumes:
  plugin_sockets: